#pragma once
#include "FieldDeclarationNode.h"
#include "IdentifierListNode.h"
#include "Node.h"
#include "NodeVisitor.h"
#include "ParameterDeclarationNode.h"
#include "TypeNode.h"
#include "TypedIdentifierNode.h"
#include "VariableDeclarationNode.h"
#include <vector>
